### ISSUE TITLE
Fix httpmethods.py

### ISSUE THREAD

**Issue by jorgeiteng** [Swafox/Flask-examples#1]
Cool, but there is an error in httpmethods.py

def do_the do_the_login():

should be

def do_the_login():

thanks

**Comment by ch4m17ux** [comment]
Hello

On the line 3 you write:

def do_the do_the_login():

This is incorrect, please fixed to:

def do_the_login():

Thank you

**Comment by Swafox** [comment]
Thank you for reporting!
Fixed now
